import type { components } from '@/api/generated/openapi-types'

export type SceneBindingState = components['schemas']['SceneBindingState']
export type PlaneResourceGroup = components['schemas']['PlaneResourceGroup']
export type ConflictState = components['schemas']['PlaneActiveObjectView']['conflict_state']
export type PlaneSnapshotSourceStatus = components['schemas']['PlaneSnapshotSourceStatus']
export type PlaneResourceBinding = components['schemas']['PlaneResourceBinding']
export type PlaneResource = components['schemas']['PlaneResource']
export type PlaneOrphanBinding = components['schemas']['PlaneOrphanBinding']
export type PlaneSceneDiagnostics = components['schemas']['PlaneSceneDiagnostics']
export type PlaneResourceGroups = components['schemas']['PlaneResourceGroups']
export type PlaneWorkLineIdentityV2 = components['schemas']['PlaneWorkLineIdentityV2']
export type PlaneSceneGeneratedFrom = components['schemas']['PlaneSceneGeneratedFrom']
export type PlaneSceneV2 = components['schemas']['PlaneSceneV2']
export type PlaneResourceRef = components['schemas']['PlaneResourceRef']
export type PlaneResourceState = components['schemas']['PlaneResourceState']
export type PlaneCurrentTaskV2 = components['schemas']['PlaneCurrentTaskV2']
export type PlaneCurrentTaskView = components['schemas']['PlaneCurrentTaskView']
export type PlaneSnapshotV2 = components['schemas']['PlaneSnapshotV2']
export type PlaneActiveObjectLocation = components['schemas']['PlaneActiveObjectLocation']
export type PlaneActiveObjectView = components['schemas']['PlaneActiveObjectView']
export type PlaneActiveObjectsV2 = components['schemas']['PlaneActiveObjectsV2']
