/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvancedSearchDialog: typeof import('./../components/search/AdvancedSearchDialog.vue')['default']
    AppHeader: typeof import('./../components/common/AppHeader.vue')['default']
    AppIcon: typeof import('./../components/ui/AppIcon.vue')['default']
    AppSidebar: typeof import('./../components/common/AppSidebar.vue')['default']
    BrandFeatures: typeof import('./../components/common/BrandFeatures.vue')['default']
    ConditionEditorRow: typeof import('./../components/search/ConditionEditorRow.vue')['default']
    DataTable: typeof import('./../components/ui/table/DataTable.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FavoriteList: typeof import('./../components/search/FavoriteList.vue')['default']
    LoginLogo: typeof import('./../components/common/LoginLogo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchConditionTag: typeof import('./../components/search/SearchConditionTag.vue')['default']
    SearchFieldPanel: typeof import('./../components/search/panels/SearchFieldPanel.vue')['default']
    SearchPopoverPanel: typeof import('./../components/search/SearchPopoverPanel.vue')['default']
    SearchQuickPanel: typeof import('./../components/search/panels/SearchQuickPanel.vue')['default']
    SidebarMenuItem: typeof import('./../components/common/SidebarMenuItem.vue')['default']
    SmartSearchBar: typeof import('./../components/search/SmartSearchBar.vue')['default']
    ThemeToggle: typeof import('./../components/common/ThemeToggle.vue')['default']
    TimezoneSettings: typeof import('./../components/common/TimezoneSettings.vue')['default']
  }
}
